# -*- coding: utf-8 -*-
"""funcao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0p5VaMr7wyjUbRDi7PaWaSRg0SrkQs7
"""

import numpy as np
import matplotlib.pyplot as plt

# Função
f = lambda x: 0.9*(np.exp(0.15*x)*np.cos(-0.4*x))

# Limites de integração
a = -15; b = 15

# Criando os pontos para serem plotados
x = np.linspace(a,b,100)
y = f(x)

# Plotando o gráfico
plt.plot(x,y,'r')
plt.title(r'$ f(x) = 0.9(e^{0.15x})\cos(-0.4x))$')
plt.xlabel('x')
plt.ylabel('y')
plt.axhline(color = 'gray', zorder =-1)
plt.grid(True)
plt.savefig('funcao.png')
plt.show()